[project]
name = "archonkit"
version = "0.1.0"
description = "A FastAPI app scaffolding toolkit"
authors = ["Kei Siatong"]
requires-python = ">=3.8"
dependencies = [
  "click>=8.0.0",
]

[project.scripts]
archonkit = "archonkit.cli:archonkit"
